<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXogtmkR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXogtmkR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXogtmkR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXogtmkR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXogtmkR\App_KernelDevDebugContainer([
    'container.build_hash' => 'XogtmkR',
    'container.build_id' => '4078d22d',
    'container.build_time' => 1732007578,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXogtmkR');
